source 'http://rubygems.org'
ruby '2.0.0'

gem 'rack-contrib', :git => 'git://github.com/rack/rack-contrib.git'
gem 'sinatra'
gem 'unicorn'
gem 'sass', '~> 3.4.0.rc.1'
gem 'compass', "~>1.0.0.alpha.18"
gem 'ffi', "= 1.9.0"
gem 'sassmeister', :github => 'SassMeister/ruby-compiler'
#gem 'sassmeister', :path => '../sassmeister-compiler'

group :development, :test do
  gem 'rake'
  gem 'pry-remote'
  gem 'thor'
  gem 'rack-test'
end

group :production do
  gem 'newrelic_rpm'
end

group :application do
  gem 'singularity-quick-spanner'
  gem 'color-hacker'
  gem 'SassyBitwise'
  gem 'base.sass'
  gem 'flint-gs'
  gem 'bourbon-compass'
  gem 'breakpoint'
  gem 'sassy-buttons'
  gem 'singularitygs'
  gem 'stipe'
  gem 'susy'
  gem 'neat-compass'
  gem 'harsh'
  gem 'toolkit'
  gem 'color-schemer'
  gem 'css-slideshow'
  gem 'fancy-buttons'
  gem 'modular-scale'
  gem 'responsive-sass'
  gem 'salsa'
  gem 'fittext'
  gem 'rwdcalc'
  gem 'zen-grids'
  gem 'breakpoint-slicer'
  gem 'sassy-text-shadow'
  gem 'compass-blend-modes'
  gem 'jacket'
  gem 'normalize-scss', "~> 3.0.0.alpha.1"
  gem 'compass-inuit'
  gem 'compass-photoshop-drop-shadow'
  gem 'grid-coordinates'
  gem 'stitch'
  gem 'breakup'
  gem 'singularity-golden-grid'
  gem 'compass-placeholders'
  gem 'SassyLists', '2.2.1'
  gem 'sassy-maps'
  gem 'bitters-compass'
  gem 'ceaser-easing'
  gem 'compass-yiq-color-contrast'
  gem 'bootstrap-sass'
  gem 'SassyJSON'
  gem 'SassyCast'
  gem 'singularity-extras', "~> 1.0.0.alpha.3"
  gem 'responsive-modular-scale'
  gem 'SassyStrings'
  gem 'scut'
  gem 'guff-compass'
  gem 'SassySort'
  gem 'SassyMatrix'
  gem 'quotation-marks'
  gem 'Sassifaction'
end
