---
Ark:
  :bower: ark
  :paths:
  - ark
  :version: 0.2.0
  :import:
  - ark/ark
  :fingerprint: (ark|ark/*)
  :homepage: https://github.com/drewbolles/ark
Base.Sass:
  :gem: base.sass
  :version: 1.6.0
  :import:
  - base.sass/+
  :fingerprint: base.sass
  :homepage: https://github.com/jsw0528/base.sass
Bitters:
  :gem: bitters-compass
  :version: 0.10.0
  :import:
  - bourbon/bourbon
  - neat/neat
  - bitters/bitters
  :fingerprint: (bitters|bitters/*)
  :homepage: https://github.com/jedfoster/bitters-compass
Blend Modes:
  :gem: compass-blend-modes
  :version: 0.0.2
  :import:
  - blend-modes
  :fingerprint: blend-mode*
  :homepage: https://github.com/heygrady/scss-blend-modes
Bootstrap Sass:
  :gem: bootstrap-sass
  :version: 3.3.3
  :import:
  - bootstrap
  :fingerprint: (bootstrap|bootstrap/*)
  :homepage: https://github.com/twbs/bootstrap-sass
Bourbon:
  :bower: bourbon
  :paths: 
  :version: 4.2.0
  :import:
  - bourbon/bourbon
  :fingerprint: (bourbon|bourbon/*)
  :homepage: http://bourbon.io
Box:
  :bower: box
  :paths:
  - box/sass
  :version: 0.1.2
  :import: 
  :fingerprint: ^box$
  :homepage: https://github.com/Undistraction/box
Breakpoint:
  :gem: breakpoint
  :version: 2.5.0
  :import:
  - breakpoint
  :fingerprint: breakpoint
  :homepage: https://github.com/Team-Sass/breakpoint
Breakpoint Slicer:
  :gem: breakpoint-slicer
  :version: 1.3.6
  :import:
  - breakpoint-slicer
  :fingerprint: breakpoint-slicer
  :homepage: https://github.com/lolmaus/breakpoint-slicer
Breakup:
  :gem: breakup
  :version: 1.0.2
  :import:
  - breakup
  :fingerprint: breakup
  :homepage: https://github.com/bpscott/breakup
CSShake:
  :bower: csshake
  :paths:
  - csshake/sass
  :version: 616a877957
  :import:
  - csshake
  :fingerprint: csshake
  :homepage: http://elrumordelaluz.github.io/csshake/
Ceasar Easing:
  :gem: ceaser-easing
  :version: '0.7'
  :import:
  - ceaser-easing
  :fingerprint: ceaser-easing
  :homepage: https://github.com/jhardy/compass-ceaser-easing
Color Hacker:
  :gem: color-hacker
  :version: 1.0.0
  :import:
  - color-hacker
  :fingerprint: color-hacker
  :homepage: http://github.com/imathis/color-hacker
Color Schemer:
  :gem: color-schemer
  :version: 0.2.8
  :import:
  - color-schemer
  :fingerprint: color-schemer
  :homepage: https://github.com/scottkellum/color-schemer
ColorMeSass:
  :bower: color-me-sass
  :paths:
  - color-me-sass
  :version: fd9afc6c1f
  :import: 
  :fingerprint: color-me-sass
  :homepage: 
Compass:
  :gem: compass
  :version: 1.0.3
  :import:
  - compass
  :fingerprint: (compass|compass/*)
  :homepage: http://compass-style.org
Compass Inuit:
  :gem: compass-inuit
  :version: 5.0.2
  :import:
  - compass-inuit
  :fingerprint: compass-inuit*
  :homepage: http://github.com/stephenway/compass-intuit
Compass Placeholders:
  :gem: compass-placeholders
  :version: 1.1.1
  :import:
  - compass
  - compass-placeholders
  :fingerprint: compass-placeholders
  :homepage: ''
Compass Slideshow:
  :gem: css-slideshow
  :version: 0.2.0
  :import:
  - compass
  - css-slideshow
  :fingerprint: css-slideshow
  :homepage: http://www.oddbird.net/
Fancy Buttons:
  :gem: fancy-buttons
  :version: 1.2.0
  :import:
  - fancy-buttons
  :fingerprint: fancy-buttons
  :homepage: http://github.com/imathis/fancy-buttons
Fittext:
  :gem: fittext
  :version: 0.0.5
  :import:
  - fittext
  :fingerprint: fittext
  :homepage: http://www.bookcasey.com/fittext/
Flint:
  :gem: flint-gs
  :version: 2.1.2
  :import:
  - flint
  :fingerprint: flint
  :homepage: http://flint.gs
Foundation:
  :bower: foundation
  :paths:
  - foundation/scss
  :version: 5.5.1
  :import:
  - foundation
  :fingerprint: foundation*
  :homepage: https://github.com/zurb/bower-foundation
Garnish:
  :bower: garnish
  :paths:
  - garnish/src
  :version: 0.2.1
  :import:
  - garnish
  :fingerprint: garnish
  :homepage: https://github.com/paulozoom/garnish
Grid Coordinates:
  :gem: grid-coordinates
  :version: 1.2.0
  :import:
  - grid-coordinates
  :fingerprint: grid-coordinates
  :homepage: http://grid-coordinates.com/
Guff:
  :gem: guff-compass
  :version: 1.0.0
  :import:
  - guff
  :fingerprint: guff
  :homepage: http://kenwheeler.github.io/guff/
Harsh:
  :gem: harsh
  :version: 1.0.0
  :import:
  - harsh
  :fingerprint: harsh
  :homepage: http://www.bookcasey.com/harsh/
Include Media:
  :bower: include-media
  :paths:
  - include-media/dist
  :version: 1.1.2
  :import: 
  :fingerprint: include-media
  :homepage: https://github.com/eduardoboucas/import-media
Jacket:
  :gem: jacket
  :version: 1.0.0
  :import:
  - jacket
  :fingerprint: jacket
  :homepage: http://github.com/robwierzbowski/jacket
Jeet:
  :bower: jeet
  :paths:
  - jeet/scss
  :version: 6.1.2
  :import: 
  :fingerprint: jeet
  :homepage: http://jeet.gs
Juice:
  :bower: juice
  :paths:
  - juice/dist
  :version: 1.0.0
  :import: 
  :fingerprint: juice
  :homepage: http://juicynex.us/juice
MathSass:
  :bower: mathsass
  :paths:
  - mathsass/dist
  :version: 0.9.5
  :import:
  - math
  :fingerprint: math
  :homepage: http://github.com/terkel/mathsass
Modular Scale:
  :gem: modular-scale
  :version: 2.0.5
  :import:
  - modular-scale
  :fingerprint: modular-scale
  :homepage: http://extension.com
Neat:
  :gem: neat-compass
  :version: 1.6.0
  :import:
  - bourbon/bourbon
  - neat/neat
  :fingerprint: (neat|neat/*)
  :homepage: https://github.com/jedfoster/neat-compass
Normalize SCSS:
  :gem: normalize-scss
  :version: 3.0.2
  :import:
  - normalize-scss
  :fingerprint: normalize-scss
  :homepage: https://github.com/JohnAlbin/normalize-scss
Photoshop Drop Shadow:
  :gem: compass-photoshop-drop-shadow
  :version: 0.0.1
  :import:
  - photoshop-drop-shadow
  :fingerprint: photoshop-drop-shadow
  :homepage: https://github.com/heygrady/compass-photoshop-drop-shadow
Position:
  :bower: position
  :paths:
  - position/sass
  :version: 0.2.14
  :import:
  - position
  :fingerprint: position
  :homepage: https://github.com/Undistraction/position
Quotation Marks:
  :gem: quotation-marks
  :version: 0.1.1
  :import:
  - quotation-marks
  :fingerprint: quotation-marks
  :homepage: http://quotation-marks.org
Responsive Calculator:
  :gem: rwdcalc
  :version: 0.0.2
  :import:
  - rwdcalc
  :fingerprint: rwdcalc
  :homepage: http://rwdcalc.com
Responsive Modular Scale:
  :gem: responsive-modular-scale
  :version: 0.2.1
  :import:
  - modular-scale
  - responsive-modular-scale
  :fingerprint: responsive-modular-scale
  :homepage: http://github.com/gakimball/responsive-modular-scale
Responsive Sass:
  :gem: responsive-sass
  :version: 0.1.1
  :import:
  - responsive-sass
  :fingerprint: responsive-sass
  :homepage: http://ntreadway.github.com/responsive-sass/welcome
Salsa:
  :gem: salsa
  :version: 0.0.1
  :import:
  - salsa
  :fingerprint: salsa
  :homepage: http://tsi.github.com/Salsa/
Sass A11Y:
  :gem: sass-a11y
  :version: 0.1.0
  :import:
  - a11y
  :fingerprint: a11y
  :homepage: https://github.com/Team-Sass/sass-a11y
Sass Color Helpers:
  :bower: sass-color-helpers
  :paths:
  - sass-color-helpers/stylesheets
  :version: 2.0.0
  :import:
  - color-helpers
  :fingerprint: color-helpers
  :homepage: https://github.com/voxpelli/sass-color-helpers
Sassifaction:
  :gem: Sassifaction
  :version: 0.0.4
  :import:
  - Sassifaction
  :fingerprint: Sassifaction
  :homepage: https://github.com/sturobson/Sassifaction
Sassy Buttons:
  :gem: sassy-buttons
  :version: 0.2.6
  :import:
  - sassy-buttons
  :fingerprint: sassy-buttons
  :homepage: http://www.jaredhardy.com/sassy-buttons
Sassy Maps:
  :gem: sassy-maps
  :version: 0.4.0
  :import:
  - sassy-maps
  :fingerprint: sassy-maps
  :homepage: https://github.com/Snugug/Sassy-Maps
Sassy Text Shadow:
  :gem: sassy-text-shadow
  :version: 0.0.4
  :import:
  - compass
  - sassy-text-shadow
  :fingerprint: sassy-text-shadow
  :homepage: http://sassymothereffingtextshadow.com
Sassy-Gridlover:
  :bower: sassy-gridlover
  :paths:
  - sassy-gridlover/sassy-gridlover
  :version: 1.1.0
  :import:
  - sassy-gridlover
  :fingerprint: sassy-gridlover
  :homepage: https://github.com/hiulit/Sassy-Gridlover
Sassy-Math:
  :gem: sassy-math
  :version: 1.5.1
  :import:
  - sassy-math
  :fingerprint: sassy-math
  :homepage: https://github.com/scottkellum/Sassy-math
SassyBitwise:
  :gem: SassyBitwise
  :version: 1.1.2
  :import:
  - SassyBitwise
  :fingerprint: SassyBitwise
  :homepage: http://github.com/HugoGiraudel/SassyBitwise
SassyCast:
  :gem: SassyCast
  :version: 1.1.1
  :import:
  - SassyCast
  :fingerprint: SassyCast
  :homepage: https://github.com/HugoGiraudel/SassyCast/
SassyJSON:
  :gem: SassyJSON
  :version: 1.1.8
  :import:
  - SassyJSON
  :fingerprint: SassyJSON
  :homepage: https://github.com/HugoGiraudel/SassyJSON/
SassyLists:
  :gem: SassyLists
  :version: 2.2.1
  :import:
  - SassyLists
  :fingerprint: SassyLists
  :homepage: http://sassylists.com/
SassyMatrix:
  :gem: SassyMatrix
  :version: 1.0.1
  :import:
  - matrix
  :fingerprint: matrix
  :homepage: https://github.com/HugoGiraudel/SassyMatrix/
SassySort:
  :gem: SassySort
  :version: 1.0.0
  :import:
  - SassySort
  :fingerprint: SassySort
  :homepage: https://github.com/HugoGiraudel/SassySort/
SassyStrings:
  :gem: SassyStrings
  :version: 1.1.4
  :import:
  - SassyString
  :fingerprint: SassyString
  :homepage: https://github.com/HugoGiraudel/SassyStrings
Scut:
  :gem: scut
  :version: 1.1.0
  :import:
  - scut
  :fingerprint: scut
  :homepage: http://davidtheclark.github.io/scut/
Singularity Extras:
  :gem: singularity-extras
  :version: 1.0.0
  :import:
  - singularitygs
  - singularity-extras
  :fingerprint: singularity-extras
  :homepage: http://singularity.gs
Singularity Quick Spanner:
  :gem: singularity-quick-spanner
  :version: 0.1.3
  :import:
  - singularitygs
  - singularity-quick-spanner
  - breakpoint-slicer
  :fingerprint: singularity-quick-spanner
  :homepage: https://github.com/lolmaus/singularity-quick-spanner
Singularity.gs:
  :gem: singularitygs
  :version: 1.5.1
  :import:
  - singularitygs
  :fingerprint: singularitygs
  :homepage: http://singularity.gs
Stipe:
  :gem: stipe
  :version: 0.0.6.4
  :import:
  - stipe/manifest
  - stipe/grid/extends
  :fingerprint: (stipe|stipe/*)
  :homepage: https://github.com/Toadstool-Stipe/stipe
Stitch:
  :gem: stitch
  :version: 0.1.4
  :import:
  - stitch
  :fingerprint: stitch
  :homepage: https://github.com/anthonyshort/stitch-css
Sunglass:
  :bower: sunglass
  :paths:
  - sunglass
  :version: 3.0.5
  :import:
  - sunglass
  :fingerprint: sunglass
  :homepage: https://github.com/devatrox/Sunglass
Susy:
  :gem: susy
  :version: 2.2.2
  :import:
  - susy
  :fingerprint: susy
  :homepage: http://susy.oddbird.net/
Toolkit:
  :gem: toolkit
  :version: 2.7.0
  :import:
  - toolkit
  :fingerprint: toolkit
  :homepage: https://github.com/Snugug/toolkit
'True':
  :bower: 'true'
  :paths:
  - true/sass
  :version: 1.0.1
  :import:
  - 'true'
  :fingerprint: 'true'
  :homepage: http://ericsuzanne.com/true
Typecsset:
  :bower: typecsset
  :paths:
  - typecsset
  :version: 0.3.0
  :import:
  - typecsset
  :fingerprint: typecsset
  :homepage: https://github.com/csswizardry/typecsset
Typesettings:
  :bower: typesettings
  :paths:
  - typesettings/
  :version: 2.3.1
  :import:
  - typesettings
  :fingerprint: typesettings
  :homepage: https://github.com/ianrose/typesettings
UtilityBelt:
  :bower: UtilityBelt
  :paths:
  - UtilityBelt
  :version: 1.1.0
  :import:
  - utility-belt
  :fingerprint: utility-belt
  :homepage: https://github.com/dmtintner/UtilityBelt
YIQ Color Contrast:
  :gem: compass-yiq-color-contrast
  :version: 1.1.1
  :import:
  - yiq-color-contrast
  :fingerprint: yiq-color-contrast
  :homepage: https://github.com/timhettler/compass-yiq-color-contrast
Zen Grids:
  :gem: zen-grids
  :version: '1.4'
  :import:
  - zen
  :fingerprint: (zen|zen-grids)
  :homepage: http://zengrids.com
